### PR TITLE
feat: add metadata to docker image

### PR DESCRIPTION
**Pull request by LouisBrunner**
## Description

Part of https://github.com/aica-technology/ops/issues/333

This requires https://github.com/aica-technology/docker-images/pull/104

@domire8 what's the process to release this library?

## Review guidelines

Estimated Time of Review: 4 minutes

## Checklist before merging:

- [X] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

### CODE REVIEW

**Comment by domire8** [comment]
I have to double check, but there are currently breaking changes on main, so we have to increase the major version.

Also, the goal was to transfer this to control-libraries at some point.

**Comment by LouisBrunner** [comment]
> Also, the goal was to transfer this to control-libraries at some point.

I don't mind that but it would be nice to release it so we can unblock the rest of the stack, we can merge them later?

**Review by domire8 — APPROVED** [review]
You can put that on main, the release build will happen if we create a tag/release notes.

**Review by eeberhard — APPROVED** [review]
Looks good for the short term.

Related future version of CL that will ultimately deprecate this repo:
- https://github.com/aica-technology/control-libraries/pull/190

**Pull request merged**
